# Generated by Django 4.0 on 2022-01-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheduler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=250, unique=True)),
                ('shedule', models.TextField()),
            ],
        ),
    ]
