# Generated by Django 4.0 on 2022-01-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheduler',
            name='time',
            field=models.CharField(default='00:00', max_length=250),
            preserve_default=False,
        ),
    ]
